spring:
  application:
    name: stock-service
  datasource:
    username: rootuser
    url: jdbc:mysql://mysql-db.cz9eevms0bmy.ap-south-1.rds.amazonaws.com/prana_inventory
    driverClassName: com.mysql.cj.jdbc.Driver
    password: zxcv+321
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}